target 'XDPRO' do
#响应编程框架

use_frameworks!
pod 'SDAutoLayout'
pod 'ReactiveObjC', '~> 2.1.2'
#刷新
pod'MJRefresh'
#HUD
pod'MBProgressHUD'
#图片缓存
pod'SDWebImage'
#布局
pod 'Masonry'
#网络请求复杂分装
pod 'AFNetworking'
end
